apiVersion: v1
kind: ReplicationController
metadata:
  name: alice-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alice-worker
    spec:
      containers:
       - name: alice-celery-worker
         image: diegodelemos/capreuse_worker:0.1.0
         imagePullPolicy: Always
         env:
          - name: QUEUE_ENV
            value: alice-queue
          - name: EXPERIMENT
            value: alice
          - name: SHARED_VOLUME
            value: "/k8s/alice"
         volumeMounts:
          - name: cap-alice-pv
            mountPath: "/data"
      securityContext:
        fsGroup: 0
      volumes:
       - name: cap-alice-pv
         persistentVolumeClaim:
           claimName: cap-alice-pv
#         cephfs:
#           monitors:
#            - 128.142.36.227:6790
#            - 128.142.39.77:6790
#            - 128.142.39.144:6790
#           path: "/k8s/alice"
#           user: k8s
#           secretRef:
#             name: ceph-secret
#           readOnly: false
