apiVersion: v1
kind: ReplicationController
metadata:
  name: alice-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alice-worker
    spec:
      containers:
       - name: alice-celery-worker
         image: diegodelemos/capreuse_worker:latest
         env:
          - name: QUEUE_ENV
            value: alice-queue
          - name: EXPERIMENT
            value: alice
         volumeMounts:
          - name: cap-pv
            readOnly: false
            mountPath: "/data"
      volumes:
      - name: cap-pv
        hostPath:
          path: "/data"
