apiVersion: v1
kind: ReplicationController
metadata:
  name: lhcb-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lhcp-worker
    spec:
      containers:
       - name: lhcb-celery-worker
         image: diegodelemos/capreuse_worker:kjobs
         env:
          - name: QUEUE_ENV
            value: lhcb-queue
          - name: EXPERIMENT
            value: lhcb
         volumeMounts:
          - name: cap-pv
            readOnly: false
            mountPath: "/data"
      volumes:
      - name: cap-pv
        hostPath:
          path: "/data"
