apiVersion: v1
kind: ReplicationController
metadata:
  name: lhcb-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lhcb-worker
    spec:
      containers:
       - name: lhcb-celery-worker
         image: diegodelemos/capreuse_worker:0.1.0
         imagePullPolicy: Always
         env:
          - name: QUEUE_ENV
            value: "lhcb-queue"
          - name: EXPERIMENT
            value: "lhcb"
          - name: SHARED_VOLUME
            value: "/k8s/lhcb"
         volumeMounts:
          - name: lhcb-pv
            mountPath: "/data"
      securityContext:
        fsGroup: 0
      volumes:
       - name: lhcb-pv
         cephfs:
           monitors:
            - 128.142.36.227:6790
            - 128.142.39.77:6790
            - 128.142.39.144:6790
           path: "/k8s/lhcb"
           user: k8s
           secretRef:
             name: ceph-secret
           readOnly: false
