apiVersion: v1
kind: ReplicationController
metadata:
  name: recast-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recast-worker
    spec:
      containers:
       - name: recast-celery-worker
         image: diegodelemos/capreuse_worker:kjobs
         env:
          - name: QUEUE_ENV
            value: recast-queue
          - name: EXPERIMENT
            value: recast
         volumeMounts:
          - name: cap-pv
            mountPath: "/data"
      volumes:
      - name: cap-pv
        persistentVolumeClaim:
          claimName: cap-claim
