apiVersion: v1
kind: ReplicationController
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       - name: flask
         image: diegodelemos/capreuse_web:0.2.0
         ports:
          - containerPort: 5000 
            name: "http"
         volumeMounts:
          - name: cap-pv
            mountPath: "/data"
      volumes:
       - name: cap-pv
         persistentVolumeClaim:
           claimName: cap-claim
